{% set data = load_setup_py_data() %}

package:
    name: alvra_tools
    version: {{ data["version"] }}

about:
   home: {{ data["url"] }}
   summary: {{ data["description"] }}

build:
    noarch: python

source:
    path: ..

requirements:
    build:
        - python >=3.6
        - setuptools
    run:
        - python >=3.6
        - h5py
        - numpy
        - scipy
        - sfdata
        - jungfrau_utils=3
