{% set data = load_setup_py_data() %}

package:
    name: alvra_tools
    version: {{ data['version'] }}

source:
    path: ..

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - h5py
        - numpy

about:
   home: https://github.com/paulscherrerinstitute/alvra_tools
   summary: {{ data['description'] }}
