{% set data = load_setup_py_data() %}

package:
    name: alvra_tools
    version: {{ data["version"] }}

about:
   home: {{ data["url"] }}
   summary: {{ data["description"] }}

source:
    path: ..

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - h5py
        - numpy
        - scipy
        - jungfrau_utils>=0.11


